FROM --platform=linux/amd64 python:3.11-slim

LABEL version="1.0.0"

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        python3-gmsh \
        curl && \
    rm -rf /var/lib/apt/lists/*

# Set working directory for code
WORKDIR /app

# Copy local code
COPY . .

# Create virtual environment
RUN python -m venv venv
ENV PATH="/app/venv/bin:$PATH"

# Install dependencies
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.job.txt

# Run from /
WORKDIR /
CMD ["python", "/app/job_runner.py"]
