# Job runner .dockerignore

# Exclude Flask-specific files
app.py
app_data_proc.py
gunicorn.conf.py
gunicorn.local.conf.py
requirements.txt
Dockerfile

# Exclude local/dev configs
venv*/
__pycache__/

# Exclude data directories
simulation_data/
datastorage/

# Exclude scripts and docs
bash_scripts/
*.sh
*.md

# Exclude bytecode
*.pyc
*.pyo
*.pyd

# Exclude env and system files
.env*
.DS_Store
.git
.gitignore
